// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// SendRequest is the request to send email. This data is streamed from client
// to the server.
type SendRequest struct {
	ToEmail              string   `protobuf:"bytes,1,opt,name=to_email,json=toEmail,proto3" json:"to_email,omitempty"`
	ToName               string   `protobuf:"bytes,2,opt,name=to_name,json=toName,proto3" json:"to_name,omitempty"`
	FromEmail            string   `protobuf:"bytes,3,opt,name=from_email,json=fromEmail,proto3" json:"from_email,omitempty"`
	FromName             string   `protobuf:"bytes,4,opt,name=from_name,json=fromName,proto3" json:"from_name,omitempty"`
	Subject              string   `protobuf:"bytes,5,opt,name=subject,proto3" json:"subject,omitempty"`
	Body                 []byte   `protobuf:"bytes,6,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendRequest) Reset()         { *m = SendRequest{} }
func (m *SendRequest) String() string { return proto.CompactTextString(m) }
func (*SendRequest) ProtoMessage()    {}
func (*SendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_df55bd875f135c62, []int{0}
}
func (m *SendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendRequest.Unmarshal(m, b)
}
func (m *SendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendRequest.Marshal(b, m, deterministic)
}
func (dst *SendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendRequest.Merge(dst, src)
}
func (m *SendRequest) XXX_Size() int {
	return xxx_messageInfo_SendRequest.Size(m)
}
func (m *SendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendRequest proto.InternalMessageInfo

func (m *SendRequest) GetToEmail() string {
	if m != nil {
		return m.ToEmail
	}
	return ""
}

func (m *SendRequest) GetToName() string {
	if m != nil {
		return m.ToName
	}
	return ""
}

func (m *SendRequest) GetFromEmail() string {
	if m != nil {
		return m.FromEmail
	}
	return ""
}

func (m *SendRequest) GetFromName() string {
	if m != nil {
		return m.FromName
	}
	return ""
}

func (m *SendRequest) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *SendRequest) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

// SendResponse is the response from the server after email is sent.
type SendResponse struct {
	StatusCode           int64                    `protobuf:"varint,1,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	Body                 string                   `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Headers              map[string]*ListOfString `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *SendResponse) Reset()         { *m = SendResponse{} }
func (m *SendResponse) String() string { return proto.CompactTextString(m) }
func (*SendResponse) ProtoMessage()    {}
func (*SendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_df55bd875f135c62, []int{1}
}
func (m *SendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendResponse.Unmarshal(m, b)
}
func (m *SendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendResponse.Marshal(b, m, deterministic)
}
func (dst *SendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendResponse.Merge(dst, src)
}
func (m *SendResponse) XXX_Size() int {
	return xxx_messageInfo_SendResponse.Size(m)
}
func (m *SendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendResponse proto.InternalMessageInfo

func (m *SendResponse) GetStatusCode() int64 {
	if m != nil {
		return m.StatusCode
	}
	return 0
}

func (m *SendResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *SendResponse) GetHeaders() map[string]*ListOfString {
	if m != nil {
		return m.Headers
	}
	return nil
}

// ListOfString is a list of strings
type ListOfString struct {
	Value                []string `protobuf:"bytes,1,rep,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListOfString) Reset()         { *m = ListOfString{} }
func (m *ListOfString) String() string { return proto.CompactTextString(m) }
func (*ListOfString) ProtoMessage()    {}
func (*ListOfString) Descriptor() ([]byte, []int) {
	return fileDescriptor_api_df55bd875f135c62, []int{2}
}
func (m *ListOfString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListOfString.Unmarshal(m, b)
}
func (m *ListOfString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListOfString.Marshal(b, m, deterministic)
}
func (dst *ListOfString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListOfString.Merge(dst, src)
}
func (m *ListOfString) XXX_Size() int {
	return xxx_messageInfo_ListOfString.Size(m)
}
func (m *ListOfString) XXX_DiscardUnknown() {
	xxx_messageInfo_ListOfString.DiscardUnknown(m)
}

var xxx_messageInfo_ListOfString proto.InternalMessageInfo

func (m *ListOfString) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*SendRequest)(nil), "api.SendRequest")
	proto.RegisterType((*SendResponse)(nil), "api.SendResponse")
	proto.RegisterMapType((map[string]*ListOfString)(nil), "api.SendResponse.HeadersEntry")
	proto.RegisterType((*ListOfString)(nil), "api.ListOfString")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// EmailClient is the client API for Email service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EmailClient interface {
	Send(ctx context.Context, opts ...grpc.CallOption) (Email_SendClient, error)
}

type emailClient struct {
	cc *grpc.ClientConn
}

func NewEmailClient(cc *grpc.ClientConn) EmailClient {
	return &emailClient{cc}
}

func (c *emailClient) Send(ctx context.Context, opts ...grpc.CallOption) (Email_SendClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Email_serviceDesc.Streams[0], "/api.Email/Send", opts...)
	if err != nil {
		return nil, err
	}
	x := &emailSendClient{stream}
	return x, nil
}

type Email_SendClient interface {
	Send(*SendRequest) error
	CloseAndRecv() (*SendResponse, error)
	grpc.ClientStream
}

type emailSendClient struct {
	grpc.ClientStream
}

func (x *emailSendClient) Send(m *SendRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *emailSendClient) CloseAndRecv() (*SendResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(SendResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// EmailServer is the server API for Email service.
type EmailServer interface {
	Send(Email_SendServer) error
}

func RegisterEmailServer(s *grpc.Server, srv EmailServer) {
	s.RegisterService(&_Email_serviceDesc, srv)
}

func _Email_Send_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EmailServer).Send(&emailSendServer{stream})
}

type Email_SendServer interface {
	SendAndClose(*SendResponse) error
	Recv() (*SendRequest, error)
	grpc.ServerStream
}

type emailSendServer struct {
	grpc.ServerStream
}

func (x *emailSendServer) SendAndClose(m *SendResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *emailSendServer) Recv() (*SendRequest, error) {
	m := new(SendRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Email_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Email",
	HandlerType: (*EmailServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Send",
			Handler:       _Email_Send_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "api.proto",
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_api_df55bd875f135c62) }

var fileDescriptor_api_df55bd875f135c62 = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x51, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x75, 0xbb, 0x6d, 0xd3, 0x4c, 0x72, 0x68, 0x17, 0xc1, 0x58, 0x51, 0x43, 0x10, 0xcc, 0xa9,
	0x42, 0xbd, 0x14, 0xaf, 0x52, 0xf0, 0xe0, 0x07, 0xa4, 0x3f, 0xa0, 0x6c, 0x9b, 0xa9, 0x46, 0x9b,
	0x6c, 0xcc, 0x6e, 0x84, 0xfc, 0x26, 0xff, 0x8a, 0x3f, 0x4a, 0x76, 0x37, 0x95, 0x80, 0xb7, 0x99,
	0x79, 0xf3, 0xde, 0xbe, 0x7d, 0x03, 0x2e, 0x2f, 0xb3, 0x59, 0x59, 0x09, 0x25, 0x18, 0xe5, 0x65,
	0x16, 0x7d, 0x13, 0xf0, 0x56, 0x58, 0xa4, 0x09, 0x7e, 0xd6, 0x28, 0x15, 0x3b, 0x85, 0x91, 0x12,
	0x6b, 0xcc, 0x79, 0xb6, 0x0f, 0x48, 0x48, 0x62, 0x37, 0x71, 0x94, 0x58, 0xea, 0x96, 0x9d, 0x80,
	0xa3, 0xc4, 0xba, 0xe0, 0x39, 0x06, 0x3d, 0x83, 0x0c, 0x95, 0x78, 0xe6, 0x39, 0xb2, 0x73, 0x80,
	0x5d, 0x25, 0xf2, 0x96, 0x45, 0x0d, 0xe6, 0xea, 0x89, 0xe5, 0x9d, 0x81, 0x69, 0x2c, 0xb3, 0x6f,
	0xd0, 0x91, 0x1e, 0x18, 0x6e, 0x00, 0x8e, 0xac, 0x37, 0xef, 0xb8, 0x55, 0xc1, 0xc0, 0x3e, 0xd7,
	0xb6, 0x8c, 0x41, 0x7f, 0x23, 0xd2, 0x26, 0x18, 0x86, 0x24, 0xf6, 0x13, 0x53, 0x47, 0x3f, 0x04,
	0x7c, 0xeb, 0x56, 0x96, 0xa2, 0x90, 0xc8, 0x2e, 0xc1, 0x93, 0x8a, 0xab, 0x5a, 0xae, 0xb7, 0x22,
	0x45, 0xe3, 0x98, 0x26, 0x60, 0x47, 0xf7, 0x22, 0xc5, 0x3f, 0x15, 0xeb, 0xd8, 0xd4, 0x6c, 0x01,
	0xce, 0x1b, 0xf2, 0x14, 0x2b, 0x19, 0xd0, 0x90, 0xc6, 0xde, 0xfc, 0x62, 0xa6, 0x53, 0xe9, 0x0a,
	0xcf, 0x1e, 0xec, 0xc2, 0xb2, 0x50, 0x55, 0x93, 0x1c, 0xd6, 0xa7, 0x4f, 0xe0, 0x77, 0x01, 0x36,
	0x06, 0xfa, 0x81, 0x4d, 0x1b, 0x94, 0x2e, 0xd9, 0x35, 0x0c, 0xbe, 0xf8, 0xbe, 0xb6, 0x11, 0x79,
	0xf3, 0x89, 0x51, 0x7e, 0xcc, 0xa4, 0x7a, 0xd9, 0xad, 0x54, 0x95, 0x15, 0xaf, 0x89, 0xc5, 0xef,
	0x7a, 0x0b, 0x12, 0x5d, 0x81, 0xdf, 0x85, 0xd8, 0xf1, 0x81, 0x4c, 0x42, 0x1a, 0xbb, 0xed, 0xe6,
	0x7c, 0x01, 0x03, 0x1b, 0xe4, 0x0d, 0xf4, 0xb5, 0x47, 0x36, 0xee, 0xd8, 0x35, 0x57, 0x9b, 0x4e,
	0xfe, 0x7d, 0x20, 0x3a, 0x8a, 0xc9, 0x66, 0x68, 0x0e, 0x7d, 0xfb, 0x1b, 0x00, 0x00, 0xff, 0xff,
	0x6a, 0xd9, 0xed, 0xf6, 0xf5, 0x01, 0x00, 0x00,
}
